services:
  - type: web
    name: udaansetu-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python -c "from app.seed import seed; seed()" && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        value: cb79f9cdd8d14f960d8f4a9559b3faa7
      - key: OLLAMA_ENABLED
        value: "false"
      - key: CORS_ORIGINS
        value: https://udaansetu.vercel.app
  - type: pgsql
    name: udaansetu-db
    plan: free
    databaseName: udaansetu
